version: "3.3"
services:
  traefik:
    image: "traefik:v2.10"
    container_name: "traefik"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./container-data/traefik.yml:/etc/traefik/traefik.yml"
      - "./container-data/letsencrypt:/letsencrypt"
    environment:
      CF_DNS_API_TOKEN: ${CLOUDFARE_DNS_API_TOKEN} 
      CF_API_EMAIL: ${CLOUDFARE_API_EMAIL} 
    networks:
      - reverseproxy
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik-secure.tls=true"
      - "traefik.http.routers.traefik-secure.tls.certresolver=cfresolver"
      - "traefik.http.routers.traefik-secure.tls.domains[0].main=elaine.pw"
      - "traefik.http.routers.traefik-secure.tls.domains[0].sans=*.elaine.pw"
      - "traefik.http.routers.traefik-secure.service=api@internal"
networks:
  reverseproxy:
    external: true
  traefik:
